version: '3.8'
#name is not working on some versions of docker compose
#name: transcendence

services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend/
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 3000:3000
      - 8080:8080
      - 6969:6969
    volumes:
      - ./backend/:/backend/
      - /backend/node_modules

  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    depends_on:
      - backend
    ports:
      - 4200:4200
    volumes:
      - ./frontend/:/frontend/
      - /frontend/node_modules


  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    ports:
      - 4242:5432

  postgres_admin:
    container_name: pg_admin
    image: dpage/pgadmin4:7.8
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 5050:80
